# Generated by Django 2.0.7 on 2019-03-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallowing',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
