# Generated by Django 2.0.7 on 2019-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190307_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Lütfen Birini Seçiniz'), ('yayin', 'YaYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
