# Generated by Django 2.0.7 on 2019-03-08 12:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_yayin_taslak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İçerik'),
        ),
    ]
