# Generated by Django 2.0.7 on 2019-03-08 13:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190308_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(help_text='Bu alan boş bırakılamaz', max_length=254, null=True, verbose_name='Email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='Yorum alanı', max_length=1000, null=True, verbose_name='Yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog')),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
            },
        ),
    ]
