# Generated by Django 2.0.7 on 2019-03-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderiler'},
        ),
    ]
